services:

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env.docker
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  backend:
    build: .
    environment:
      - PYTHONPATH=/src
    container_name: url_shortener
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev
    command: >
      bash -c "
      alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000
      "

networks:
  dev:

volumes:
  postgres_data: